[package]
name = "engine-library"
version = "0.1.0"
edition = "2021"

[lib]
name = "engine"
path = "src/lib.rs"
crate-type = ["dylib", "rlib"]

[dependencies]
engine-common = { path = "../core" }
tokio = "1.41.0"