[package]
name = "engine-share"
version = "0.1.0"
edition = "2024"

[dependencies]
# 序列化和反序列化数据
serde = { version = "1.0.207", features = ["derive"] }
# 处理 JSON 数据
serde_json = "1.0.124"
# serde 的派生宏
serde_derive = "1.0.207"